### ISSUE TITLE
Blank UI

### ISSUE THREAD

**Issue by senften** [PaddoSwam/AspNetCoreVersionedWebApi#1]
I cloned the repository, dotnet restore, and dotnet run and the UI display is completely blank.
From the Inspector in Firefox

> `<html><head></head><body></body></html>`

The api itself is alive. I can hit it from postman and the json files are being generated.

<pre>
{
  "swagger": "2.0",
  "info": {
    "version": "2.0",
    "title": "API Version 2.0"
  },
  "basePath": "/",
  "paths": {
    "/api/v2.0/Hello": {
      "get": {
        "tags": [
          "Hello"
        ],
        "operationId": "ApiV{versionHelloGet",
        "consumes": [],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/HelloWorldModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HelloWorldModel": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {}
}
</pre>

but the UI doesn't generate.

PS E:\senften\src\AspNetCoreVersionedWebApi\VersionedWebApi> dotnet --version
1.0.1

The console shows no errors

Suggestions?

**Comment by senften** [comment]
On Chrome, it returns a 404

<pre>
This localhost page can’t be found

No webpage was found for the web address: http://localhost:5000/swagger/ui/index.html
Search Google for localhost 5000 swagger index
HTTP ERROR 404
</pre>

**Comment by PaddoSwam** [comment]
That's unfortunate, I'm assuming you're running it from the command line.
`dotnet run`
States that it starts the application on http://localhost:5000/ but since it's an Web API project you'll need to navigate to either `http://localhost:5000/swagger/` for the swagger docs and either `http://localhost:5000/api/v1.0/hello` for version 1 or `http://localhost:5000/api/v2.0/hello` for version 2.

I have tested it on
```dotnet --version
1.0.4```
and ran from Visual Studio 2017 Community & Enterprise

**Comment by senften** [comment]
OK, thank you very much. I started from a swagger generated .net core backend and, as you can see from my original post, assumed the UI always was routed to `http://localhost:5000/swagger/ui/index.html`.
This is working as you describe on my mac. I suspect when I check this on my workstation, hitting the right, URL that it is working there as well. I'll update in the morning.

**Comment by senften** [comment]
Tom, could you do me another favor? Look at the json I posted above. I think it's wrong. I think operationId is missing the curly brace at the end of version? Would you check if you see the same thing? I realize this isn't an issue with your example.

**Comment by senften** [comment]
Tom, sorted it out. FYI, it does seem to be a bug in `<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="1.1.0-rc1"/>`
Thanks for the help

**Comment by PaddoSwam** [comment]
Had very little time, but luckily that's open source as well so you might be able to trace it down 😄
